{{ define "forum" }}


<div class='panel panel-success'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-user"></span>&nbsp; Paizo Messageboard</h3></div>
	<div class="panel-body" style='padding-left: 0; padding-bottom: 0; text-align: left;'>
		<a href='http://paizo.com/threads/rzs2lbkj&amp;page=last?My-new-character-sheets-for-Pathfinder'><img src='/images/paizo.png' width='260'></a>
	</div>
	<div class="panel-footer">
		<a href='http://paizo.com/threads/rzs2lbkj&amp;page=last?My-new-character-sheets-for-Pathfinder'><span class='glyphicon glyphicon-bullhorn'></span>&nbsp; Talk with the public here</a>
	</div>
</div>

{{ end }}
