{{ define "github" }}

<div class='panel panel-success'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-pencil"></span>&nbsp; Open Source</h3></div>
	<div class="panel-body" style='padding: 1em; text-align: center;'>
		<a href='https://github.com/marcusatbang/charactersheets'><img src='/images/github-logo.png' width='240'></a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/marcusatbang/charactersheets'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Main project</a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/marcusatbang/charactersheets-pdf'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; PDF export</a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/marcusatbang/charactersheets-website'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Website</a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/marcusatbang/charactersheets-translator'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Translator</a>
	</div>
</div>

{{ end }}