{{ define "help" }}

<div class='panel panel-primary'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-question-sign"></span>&nbsp; Help</h3></div>
	<div class='panel-body'>
		<p><a href='/help/1'>How to translate</a></p>
		<p><a href='/help/2'>How to compare translations</a></p>
		<p><a href='/help/3'>How to comment on translations</a></p>
		<p><a href='/help/4'>How to check my progress</a></p>
	</div>
	<div class="panel-footer">
		<a class='btn btn-link btn-sm' href='/help'><span class="glyphicon glyphicon-question-sign"></span>&nbsp; More help</a> &nbsp; 
		<a class='btn btn-link btn-sm' href='/help/ask'><span class="glyphicon glyphicon-comment"></span>&nbsp; Ask a question</a>
	</div>
</div>

{{ end }}