{{ define "recent" }}

<div class='panel panel-info'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-globe"></span>&nbsp; Recent Translations</h3></div>
	<table class='table'>
	<tr>
		<td>Knowledge: Dungeoneering</td>
		<td><img src='http://www.gravatar.com/avatar/85da34890f23a1fbd629bacc8b6bb81a?s=24' class="gravatar-24"></td>
		<td><img src='/images/flags/it.png'></td>
		<td>Conoscenze: Dungeon</td>
	</tr>
	</table>
	<div class='panel-footer'>
		<a class='btn btn-primary btn-sm' href='/translate'><span class="glyphicon glyphicon-globe"></span>&nbsp; Translate</a> 
	</div>
</div>

{{ end }}