{{ define "slack" }}


<div class='panel panel-success'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-user"></span>&nbsp; Collaborate</h3></div>
	<div class="panel-body" style='padding-top: 0; text-align: center;'>
		<a href='https://charactersheets.slack.com/'><img src='/images/slack_rgb.png' width='260'></a>
	</div>
	<div class="panel-footer">
		<a href='https://charactersheets.slack.com/'><span class='glyphicon glyphicon-bullhorn'></span>&nbsp; Talk with your fellow translators here</a>
	</div>
</div>

{{ end }}